/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package thongke;

import com.mycompany.java_qlnt.helper.Helper;
import com.mycompany.java_qlnt.helper.util;
import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.h2.tools.SimpleResultSet;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author chien
 */
public class TKPhong extends javax.swing.JPanel {

    /**
     * Creates new form TKPhong
     */
    Helper help = new Helper();
    ResultSet data = new SimpleResultSet() ;
    util util = new util();
    ArrayList<JLabel> listLabel = new ArrayList<>();
    ArrayList<Integer> listNum = new ArrayList<>();
    public TKPhong() {
        initComponents();
        getAllRoom();
        getData();
        addLabelList();
        chart();
        addNumValue();
        
        
    }
    
    private void addLabelList( ) {
        listLabel.add(dangCoc);
        listLabel.add(dangSuDung);
        listLabel.add(phongTrong);
        listLabel.add(sapHetHopDong);
    }
    
    private void addNumValue() {
        int all = 0;
        for (int i = 0; i < listNum.size(); i++) {
            int num = listNum.get(i);
            listLabel.get(i).setText(num+"");
            all+=num;
        }
        luongPhong.setText(all+"");
    }
    
     private void getAllRoom() {
        String sql = "select maPhong, tang, tinhTrang from PhongTro";
        ResultSet room = help.select(sql);
        util.loadDataToTable(room, jTable1);
    }
     
    private void getData() {
        String sql = "select count(tinhTrang) as soLuong, tinhTrang from PhongTro group by tinhTrang order by tinhTrang;";
        data = help.select(sql);
    }
    
    public  void chart() {
        JFreeChart pieChart = createPieChart(createDataset());
        org.jfree.chart.ChartPanel chartPanel = new org.jfree.chart.ChartPanel(pieChart);
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(chartPanel);
        jPanel1.validate();
    }
     
     private  PieDataset createDataset() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        try {
            while(data.next()) {
                
                int num = data.getInt("soLuong");
                listNum.add(num);
                dataset.setValue(data.getString("tinhTrang"), num);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TKPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dataset;
    }

    private  JFreeChart createPieChart(PieDataset dataset) {
        JFreeChart chart = ChartFactory.createPieChart(
                "".toUpperCase(),
                dataset, true, true, true);
        return chart;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        luongPhong = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dangCoc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dangSuDung = new javax.swing.JLabel();
        vsfs = new javax.swing.JLabel();
        phongTrong = new javax.swing.JLabel();
        cá = new javax.swing.JLabel();
        sapHetHopDong = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Tầng", "Tình trạng"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Số lượng phòng:");

        luongPhong.setText("0");

        jLabel2.setText("Đang cọc:");

        dangCoc.setText("0");

        jLabel3.setText("Đang sử dụng:");

        dangSuDung.setText("0");

        vsfs.setText("Phòng trống:");

        phongTrong.setText("0");

        cá.setText("Sắp hết hợp đồng:");

        sapHetHopDong.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(luongPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dangCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dangSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vsfs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phongTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cá)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sapHetHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(luongPhong)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(dangCoc)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dangSuDung)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vsfs)
                                .addComponent(phongTrong)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cá)
                                    .addComponent(sapHetHopDong))))))
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cá;
    private javax.swing.JLabel dangCoc;
    private javax.swing.JLabel dangSuDung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel luongPhong;
    private javax.swing.JLabel phongTrong;
    private javax.swing.JLabel sapHetHopDong;
    private javax.swing.JLabel vsfs;
    // End of variables declaration//GEN-END:variables
}
