/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.java_qlnt.QLPhong;


import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author chien
 */
public class ListPhong extends javax.swing.JPanel {

    /**
     * Creates new form ListPhong
     */
    public ListPhong(ResultSet listRoom) {
        System.out.println("list phong"); 
        initComponents();
        jPanel1.removeAll();
        this.listRoom = listRoom;
        showList();
    }
    
    private ResultSet listRoom;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());
        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    private void showList() {
        int tang = 1;
        int count = 0;
//        int max = 0;
//        ArrayList<Integer> soPhongMoiTang = new ArrayList<>();
        try {
            while(listRoom.next()) {
                String maPhong = listRoom.getString("maPhong");
                String tinhTrang = listRoom.getString("tinhTrang");
                if(maPhong.charAt(1) - '0' == tang) {
                    ++count;
                }
                //xử lý in theo từng tầng(Khó lm sau
//                    soPhongMoiTang.add(0,count);
//                    for (int i = 0; i < soPhongMoiTang.size(); i++) {
//                        if(count > soPhongMoiTang.get()) {
//                            max = count;
//                            int num = count - soPhongMoiTang.get(1);
//                            
//                        }
//                    }
//                    
//                    count = 0;
//                }
                Phong phong = new Phong(maPhong, tinhTrang);
                addPhong(phong);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ListPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        int with = 102*(count+1);
        jPanel1.setPreferredSize(new Dimension(with, 468));
        ShowList();
    }
    
    private void addPhong(JPanel childpanel) {
        jPanel1.setLayout(new FlowLayout());
        jPanel1.add(childpanel);
    }
    
    private void ShowList() {
        jPanel1.validate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
