/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.java_qlnt.QLPhong;

import java.awt.Color;
import java.sql.ResultSet;

/**
 *
 * @author chien
 */
public class TinhTrangPhong extends javax.swing.JPanel {

    /**
     * Creates new form TinhTrangPhong
     */
//    public TinhTrangPhong(ResultSet result) {
//        initComponents();
//        this.tenPhong = tenP;
//        this.tinhTrangPhong = tinhTrang;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private String tenPhong = "";
    private String tinhTrangPhong = "";
    
//    public void setItem() {
//        TenPhong.setText(tenPhong);
//        TinhTrangHienTai.setText(tinhTrangPhong);
//        switch(tinhTrangPhong.toLowerCase()) {
//            case "đang sử dụng" -> this.setBackground(Color.RED);
//            case "phòng trống" -> this.setBackground(Color.GREEN);
//            case "đã cọc" -> this.setBackground(Color.YELLOW);
//            case "sắp hết hợp đồng" -> this.setBackground(Color.ORANGE);
//        }
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
